#! /bin/sh

sxhkd &
picom -b --experimental-backends &
xrandr --output eDP-1 --mode 1600x900 &
xrandr --output HDMI-2 --auto --right-of eDP-1 &
feh --bg-fill --randomize ~/Pictures/Backgrounds/* &
teams &
telegram &
polybar example &

bspc monitor eDP-1 -d I II III IV V
bspc monitor HDMI-2 -d I II III IV V
#VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

